apiVersion: v1
kind: Pod
metadata:
  name: hello-flask
  labels:
    app: hello-flask
spec:
  containers:
  - name: hello-flask #CHNAGED#
    image: someone12dd/my_flask
    ports:
    - containerPort: 5000
