# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-config
# data:
#   custom.ini: |
#     [server]
#     domain = localhost
#     root_url = http://localhost:3000
#     http_port = 3000

#     [security]
#     admin_user = admin
#     admin_password = 1234

#     [auth]
#     disable_login_form = false

#     [smtp]
#     enabled = false
#   datasources.yaml: |
#     apiVersion: 1
#     datasources:
#       - name: Prometheus
#         type: prometheus
#         url: http://prometheus-service:9090
#         access: proxy
#         isDefault: true
#   dashboards.yaml: |
#     apiVersion: 1
#     providers:
#       - name: 'default'
#         orgId: 1
#         folder: ''
#         type: file
#         disableDeletion: false
#         editable: true
#         options:
#           path: /var/lib/grafana/dashboards
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    http_addr = 0.0.0.0
    http_port = 3000
    protocol = http
    domain = localhost
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    serve_from_sub_path = false

    [database]
    type = sqlite3
    host = 127.0.0.1:3306
    name = grafana
    user = root
    password =
    ssl_mode = disable
    path = grafana.db

    [auth]
    disable_login_form = false
    disable_signout_menu = false

    [log]
    mode = console
