apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
spec:
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000  # This will expose the service on port 30000 on your node
  type: NodePort